# Generated by Django 5.1.6 on 2025-08-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='locations.administrativeregion'),
        ),
        migrations.CreateModel(
            name='ShippingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rates', to='locations.administrativeregion')),
                ('origin_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_rates', to='locations.administrativeregion')),
            ],
            options={
                'unique_together': {('origin_region', 'destination_region')},
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('fast', 'Nhanh'), ('normal', 'Trung bình')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='locations.shippingroute')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='locations.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='locations.ward')),
            ],
        ),
    ]
