# Generated by Django 5.2.4 on 2025-08-30 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='province',
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='locations.district'),
        ),
    ]
