# Generated by Django 5.2.4 on 2025-08-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_ward_province_ward_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='region',
            new_name='administrative_region',
        ),
    ]
