# Generated by Django 5.2.4 on 2025-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_userlocation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
