# Generated by Django 5.2.4 on 2025-08-31 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_userlocation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='locations.district'),
            preserve_default=False,
        ),
    ]
