# Generated by Django 5.1.6 on 2025-08-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_owner_alter_orderdetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_methods',
            new_name='delivery_method',
        ),
    ]
