# Generated by Django 5.1.6 on 2025-08-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_delivery_methods_order_delivery_method'),
        ('locations', '0002_province_region_shippingroute_shippingrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.province'),
        ),
    ]
