# Generated by Django 5.2.4 on 2025-08-21 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_province'),
        ('locations', '0002_province_region_shippingroute_shippingrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='delivery_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='locations.shippingroute'),
            preserve_default=False,
        ),
    ]
