# Generated by Django 5.1.6 on 2025-08-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderdetail_delivery_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
    ]
