# Generated by Django 5.1.6 on 2025-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='delivery_method',
            field=models.CharField(choices=[('fast', 'Nhanh'), ('normal', 'Trung bình')], default='normal', max_length=10),
        ),
    ]
