# Generated by Django 5.1.6 on 2025-08-22 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_total'),
        ('locations', '0002_province_region_shippingroute_shippingrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.ward'),
        ),
    ]
