# Generated by Django 5.2.4 on 2025-08-30 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_order_ward'),
        ('locations', '0005_rename_region_province_administrative_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
    ]
