# Generated by Django 5.2.4 on 2025-08-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_distict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='distict',
            new_name='district',
        ),
    ]
