# Generated by Django 5.2.4 on 2025-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_rename_distict_order_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
