# Generated by Django 5.2.4 on 2025-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_status',
            field=models.TextField(choices=[('pending', 'Chờ giao hàng'), ('confirm', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('packed', 'Đã đóng gói'), ('shipped', 'Đang giao hàng'), ('in_transit', 'Đang trên đường vận chuyển'), ('out_of_delivery', 'Ra khỏi kho'), ('delivered', 'Đã giao hàng'), ('failded_delivery_attempt', 'Giao hàng thất bại'), ('returned_to_sender', 'Trả hàng'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending'),
        ),
    ]
