# Generated by Django 5.2.4 on 2025-09-01 10:39

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_orderdetail_delivery_persion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailConfirmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_confirm', to='checkout.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
