# Generated by Django 5.1.6 on 2025-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_alter_orderdetail_delivery_persion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='delivery_persion',
            new_name='delivery_person',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_status',
            field=models.TextField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang chuẩn bị hàng'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao'), ('returned_to_sender', 'Trả hàng'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending'),
        ),
    ]
