# Generated by Django 5.2.4 on 2025-09-04 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_rename_delivery_persion_orderdetail_delivery_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'delivery_person'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='delivery_status',
            field=models.TextField(choices=[('pending', 'Chờ xử lý'), ('confirm', 'Đã xác nhận'), ('processing', 'Đang chuẩn bị hàng'), ('shipped', 'Đang giao hàng'), ('delivered', 'Đã giao'), ('returned_to_sender', 'Trả hàng'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending'),
        ),
    ]
