# Generated by Django 5.0.6 on 2025-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_orderdetail_delivery_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('momo', 'Momo')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
