# Generated by Django 5.0.6 on 2025-09-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
    ]
