# Generated by Django 5.0.6 on 2025-09-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_remove_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'vnpay')], default='cod', max_length=20),
        ),
    ]
