# Generated by Django 5.2.4 on 2025-08-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rate_order_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageOptionValue',
            new_name='OptionValueImage',
        ),
    ]
