# Generated by Django 5.2.4 on 2025-08-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_imageoptionvalue_optionvalueimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalueimage',
            name='option_value',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.optionvalue'),
        ),
    ]
