# Generated by Django 5.2.4 on 2025-08-30 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_region_province_administrative_region'),
        ('products', '0006_alter_option_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='locations.district'),
        ),
    ]
