# Generated by Django 5.2.4 on 2025-07-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_options_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='products.option'),
        ),
    ]
