# Generated by Django 5.0.6 on 2025-09-08 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_alter_order_payment_method'),
        ('products', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='order_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate', to='checkout.orderdetail'),
        ),
    ]
