# Generated by Django 5.0.6 on 2025-09-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_rate_order_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate_avg',
        ),
    ]
