# Generated by Django 5.0.6 on 2025-09-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_descriptions', to='products.product'),
        ),
    ]
