# Generated by Django 5.0.6 on 2025-09-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_description_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='Descriptions',
        ),
    ]
