# Generated by Django 5.0.6 on 2025-09-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_description_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='products.product'),
        ),
    ]
