# Generated by Django 5.1.6 on 2025-08-10 07:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_supplier_alter_user_options_user_address_user_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.CreateModel(
            name='SupplierApproved',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
