# Generated by Django 5.2.4 on 2025-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Người bán'), ('customer', 'Người mua'), ('delivery man', 'Người giao hàng')], default='customer', max_length=20),
        ),
    ]
