# Generated by Django 5.1.6 on 2025-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Người bán'), ('customer', 'Người mua'), ('delivery person', 'Người giao hàng')], default='customer', max_length=20),
        ),
    ]
