# Generated by Django 5.2.4 on 2025-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Người bán'), ('customer', 'Người mua'), ('delivery_person', 'Người giao hàng')], default='customer', max_length=20),
        ),
    ]
