# Generated by Django 5.0.6 on 2025-09-05 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fcmtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('token',)},
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user',
        ),
    ]
