# Generated by Django 5.0.6 on 2025-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='cccd_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
