# Generated by Django 5.0.6 on 2025-09-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_auditlog_cccd_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='cccd_enc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
